// Code generated by openapi-gen; DO NOT EDIT.
import { ApiClient, type CallOptions } from "../../../core/http.js";
import type * as models from "./models.gen.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `commands` resource. Methods return the raw response envelope.
 */
export class CommandsApi extends ApiClient {
  /**
   * Delete Command by UUID
   */
  deleteCommandByUuid(uuid: string, params: CallOptions = {}): Promise<models.EmptyResponse> {
    return this.request<models.EmptyResponse>(
      {
        method: "DELETE",
        path: `/commands/${uuid}`,
      },
      params,
    );
  }

  /**
   * Delete Command Logs
   */
  deleteCommandLogsByUuid(uuid: string, params: CallOptions = {}): Promise<models.EmptyResponse> {
    return this.request<models.EmptyResponse>(
      {
        method: "DELETE",
        path: `/commands/${uuid}/logs`,
      },
      params,
    );
  }

  /**
   * Get Command by UUID
   */
  getCommandByUuid(uuid: string, params: CallOptions = {}): Promise<models.GetCommandResponse> {
    return this.request<models.GetCommandResponse>(
      {
        method: "GET",
        path: `/commands/${uuid}`,
      },
      params,
    );
  }

  /**
   * Get Command Logs
   */
  getCommandLogs(uuid: string, params: CallOptions = {}): Promise<models.CommandLogsResponse> {
    return this.request<models.CommandLogsResponse>(
      {
        method: "GET",
        path: `/commands/${uuid}/logs`,
      },
      params,
    );
  }

  /**
   * Get Raw Command Log
   */
  getRawCommandLog(
    uuid: string,
    stream: models.CommandLogStream,
    params: {
      Range?: string;
    } & CallOptions = {},
  ): Promise<Uint8Array> {
    return this.bytes(
      {
        method: "GET",
        path: `/commands/${uuid}/logs/raw/${stream}`,
      },
      {
        ...params,
        headers: {
          ...(params["Range"] !== undefined ? { Range: String(params["Range"]) } : {}),
          ...params.headers,
        },
      },
    );
  }

  /**
   * List Commands
   */
  listCommands(params: CallOptions = {}): Promise<models.ListCommandsResponse> {
    return this.request<models.ListCommandsResponse>(
      {
        method: "GET",
        path: `/commands`,
      },
      params,
    );
  }

  /**
   * Start Command
   */
  runCommand(
    params: {
      body: models.RunCommandRequest;
    } & CallOptions,
  ): Promise<models.RunCommandResponse> {
    return this.request<models.RunCommandResponse>(
      {
        method: "POST",
        path: `/commands`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Signal Command
   */
  signalCommand(
    uuid: string,
    params: {
      body: models.CommandSignalRequest;
    } & CallOptions,
  ): Promise<models.EmptyResponse> {
    return this.request<models.EmptyResponse>(
      {
        method: "POST",
        path: `/commands/${uuid}/signal`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Wait for Command
   */
  waitForCommand(uuid: string, params: CallOptions = {}): Promise<models.EmptyResponse> {
    return this.request<models.EmptyResponse>(
      {
        method: "POST",
        path: `/commands/${uuid}/wait`,
      },
      params,
    );
  }

  /**
   * Wait for Command with Timeout
   */
  waitForCommandWithTimeout(
    uuid: string,
    params: {
      body: models.CommandWaitTimeoutRequest;
    } & CallOptions,
  ): Promise<models.EmptyResponse> {
    return this.request<models.EmptyResponse>(
      {
        method: "POST",
        path: `/commands/${uuid}/wait_timeout`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Write Command Stdin
   */
  writeCommandStdin(
    uuid: string,
    params: {
      body: models.CommandStdinRequest;
    } & CallOptions,
  ): Promise<models.EmptyResponse> {
    return this.request<models.EmptyResponse>(
      {
        method: "POST",
        path: `/commands/${uuid}/stdin`,
        body: params.body,
      },
      params,
    );
  }
}
