// Code generated by openapi-gen; DO NOT EDIT.
import { ApiClient, type CallOptions } from "../../../core/http.js";
import type * as models from "./models.gen.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `fs` resource. Methods return the raw response envelope.
 */
export class FsApi extends ApiClient {
  /**
   * Create Directory
   */
  createDirectory(
    params: {
      body: models.MkdirRequest;
    } & CallOptions,
  ): Promise<models.EmptyResponse> {
    return this.request<models.EmptyResponse>(
      {
        method: "POST",
        path: `/fs/mkdir`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Read File
   */
  readFile(
    params: {
      body: models.ReadFileRequest;
    } & CallOptions,
  ): Promise<models.ReadFileResponse> {
    return this.request<models.ReadFileResponse>(
      {
        method: "POST",
        path: `/fs/read`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Read Raw File
   */
  readRawFile(
    params: {
      body: models.ReadFileRequest;
    } & CallOptions,
  ): Promise<Uint8Array> {
    return this.raw(
      {
        method: "POST",
        path: `/fs/read_raw`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Upload File
   */
  uploadFile(
    params: {
      body: models.UploadFileRequest;
    } & CallOptions,
  ): Promise<models.EmptyResponse> {
    return this.request<models.EmptyResponse>(
      {
        method: "POST",
        path: `/fs/upload`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Write File
   */
  writeFile(
    params: {
      body: models.WriteFileRequest;
    } & CallOptions,
  ): Promise<models.EmptyResponse> {
    return this.request<models.EmptyResponse>(
      {
        method: "POST",
        path: `/fs/write`,
        body: params.body,
      },
      params,
    );
  }
}
