// Code generated by openapi-gen; DO NOT EDIT.
//
// Type definitions for the Unikraft Cloud API, generated from the OpenAPI
// specification. These mirror the wire format exactly.

/**
 * The output stream to read raw bytes from.
 */

export type CommandLogStream = "stdout" | "stderr";

/**
 * The collected output of a command.
 */

export interface CommandLogsData {
  /**
   * The requested part of the standard output stream, base64-encoded.
   */
  stdout: string;
  /**
   * The requested part of the standard error stream, base64-encoded.
   */
  stderr: string;
  /**
   * The total number of bytes available in the standard output stream.
   */
  stdout_available: number;
  /**
   * The total number of bytes available in the standard error stream.
   */
  stderr_available: number;
}

/**
 * The byte range of a single output stream to return.
 */

export interface CommandLogsRange {
  /**
   * The first byte of the stream to return.
   */
  offset: number;
  /**
   * The maximum number of bytes to return. When omitted, everything from
   * `offset` to the end of the stream is returned.
   */
  limit?: number;
}

/**
 * The (optional) request body limiting which parts of the output streams are
 * returned. When omitted, both streams are returned in their entirety.
 */

export interface CommandLogsRequest {
  /**
   * The part of the standard output stream to return.
   */
  stdout: CommandLogsRange;
  /**
   * The part of the standard error stream to return.
   */
  stderr: CommandLogsRange;
}

/**
 * The response to fetching the output of a command. `404` is returned, with an
 * empty body, when no command with the given UUID exists. `410` is returned,
 * with an
 * empty body, if the command's logs have been deleted.
 */

export interface CommandLogsResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the status.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data: CommandLogsData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  op_time_us: number;
}

/**
 * The request to send a signal to a command.
 */

export interface CommandSignalRequest {
  /**
   * The signal to send, either as a number or as a name, with or without the
   * `SIG` prefix, e.g. `15`, `TERM` or `SIGTERM`.
   */
  signal: number | string;
}

/**
 * The request to feed data into a command's standard input.
 */

export interface CommandStdinRequest {
  /**
   * The bytes to feed into standard input, base64-encoded.
   */
  data: string;
  /**
   * Whether to close standard input after injecting `data`.
   */
  eof?: boolean;
}

/**
 * The request to wait for a command to finish, up to a timeout.
 */

export interface CommandWaitTimeoutRequest {
  /**
   * The maximum time to wait, in seconds. Decimals are accepted.
   */
  timeout_s: number;
}

/**
 * A response which carries no data of its own. `data` is `null`; the outcome
 * of
 * the request is the HTTP status code.
 */

export interface EmptyResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the status.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data: unknown;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  op_time_us: number;
}

/**
 * The encoding of the data written to a file.
 */

export type FileEncoding = "utf-8" | "base64";

/**
 * The state of a single command.
 */

export interface GetCommandData {
  /**
   * The UUID of the command.
   */
  uuid: string;
  /**
   * The command line the command was started with.
   */
  cmdline: string;
  /**
   * The current working directory, if supplied at startup, else null
   */
  cwd: string | null;
  /**
   * Environment variables, if supplied at startup, else null
   */
  env: Record<string, string> | null;
  /**
   * The exit code of the command. It is `null` while the command is still
   * running.
   */
  exitcode: number | null;
}

/**
 * The response to inspecting a command. `404` is returned, with an empty body,
 * when no command with the given UUID exists.
 */

export interface GetCommandResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the status.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data: GetCommandData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  op_time_us: number;
}

/**
 * The known commands.
 */

export interface ListCommandsData {
  /**
   * The UUIDs of all known commands, in the order they were started.
   */
  commands: string[];
}

/**
 * The response to listing the commands known to the sandbox.
 */

export interface ListCommandsResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the status.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data: ListCommandsData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  op_time_us: number;
}

/**
 * The request to create a directory in the sandbox filesystem.
 */

export interface MkdirRequest {
  /**
   * The absolute path of the directory to create.
   */
  path: string;
  /**
   * Whether to create missing parent directories.
   */
  parents: boolean;
}

/**
 * The contents of a file.
 */

export interface ReadFileData {
  /**
   * The contents of the file, base64-encoded.
   */
  contents: string;
}

/**
 * The request to read a file from the sandbox filesystem.
 */

export interface ReadFileRequest {
  /**
   * The absolute path of the file to read.
   */
  path: string;
}

/**
 * The response to reading a file. `500` is returned when the file could not be
 * read.
 */

export interface ReadFileResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the status.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data: ReadFileData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  op_time_us: number;
}

/**
 * The error response message for an API request.
 */

export interface ResponseError {
  /**
   * The HTTP status code of the error.
   */
  status: number;
}

/**
 * The response status of an API request.
 */

export type ResponseStatus = "success" | "error" | "partial_success";

/**
 * The identity of a newly started command.
 */

export interface RunCommandData {
  /**
   * The UUID assigned to the newly started command.
   */
  uuid: string;
}

/**
 * The request to start a command in the sandbox.
 */

export interface RunCommandRequest {
  /**
   * The command line to run, as passed to the shell.
   */
  cmd: string;
  /**
   * (OPTIONAL) Current working directory
   */
  cwd?: string;
  /**
   * (OPTIONAL) Environment variables
   */
  env?: Record<string, string>;
}

/**
 * The response to starting a command. `500` is returned when the command could
 * not be spawned.
 */

export interface RunCommandResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the status.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data: RunCommandData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  op_time_us: number;
}

/**
 * The request to upload a file to the sandbox filesystem.
 */

export interface UploadFileRequest {
  /**
   * Path where to upload the file.
   */
  path: string;
  /**
   * Name of uploaded file; will be used if `path` is a directory.
   */
  filename: string;
  /**
   * Whether to create parent directories of `path`.
   */
  parents: boolean;
  /**
   * The encoding of `data`.
   */
  encoding: FileEncoding;
  /**
   * The data to write, in the given encoding
   */
  data: string;
}

/**
 * The request to write a file in the sandbox filesystem.
 */

export interface WriteFileRequest {
  /**
   * The absolute path of the file to write. It is created if missing.
   */
  path: string;
  /**
   * Whether to append to the file instead of truncating it.
   */
  append: boolean;
  /**
   * The encoding of `data`.
   */
  encoding: FileEncoding;
  /**
   * The data to write, in the given encoding.
   */
  data: string;
}
