// Code generated by openapi-gen; DO NOT EDIT.
import { ApiClient, type CallOptions } from "../../core/http.js";
import type * as models from "./models.gen.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `Auth` resource. Methods return the raw response envelope.
 */
export class AuthApi extends ApiClient {
  /**
   * Check Authorization of Sign-In Request
   */
  checkAuthorization(
    params: {
      body: models.CheckAuthorizationRequest;
    } & CallOptions,
  ): AsyncGenerator<models.CheckAuthorizationResponse, void, void> {
    return this.stream<models.CheckAuthorizationResponse>(
      {
        method: "POST",
        path: `/v1/auth/check`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Get Authorization Status
   */
  getAuthorization(params: CallOptions = {}): Promise<models.GetAuthorizationResponse> {
    return this.request<models.GetAuthorizationResponse>(
      {
        method: "GET",
        path: `/v1/auth`,
      },
      params,
    );
  }

  /**
   * Request Sign-In
   */
  requestSignin(
    params: {
      body: models.RequestSigninRequest;
    } & CallOptions,
  ): Promise<models.RequestSigninResponse> {
    return this.request<models.RequestSigninResponse>(
      {
        method: "POST",
        path: `/v1/auth/signin`,
        body: params.body,
      },
      params,
    );
  }
}
