// Code generated by openapi-gen; DO NOT EDIT.
import { ApiClient, type CallOptions } from "../../core/http.js";
import type * as models from "./models.gen.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `Images` resource. Methods return the raw response envelope.
 */
export class ImagesApi extends ApiClient {
  /**
   * List Images
   */
  listImages(
    params: {
      details?: boolean;
      namespace?: string[];
    } & CallOptions = {},
  ): Promise<models.ListImagesResponse> {
    return this.request<models.ListImagesResponse>(
      {
        method: "GET",
        path: `/v1/images`,
        query: {
          details: params["details"],
          namespace: params["namespace"],
        },
      },
      params,
    );
  }
}
