// Code generated by openapi-gen; DO NOT EDIT.
import { ApiClient, type CallOptions } from "../../core/http.js";
import type * as models from "./models.gen.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `Metros` resource. Methods return the raw response envelope.
 */
export class MetrosApi extends ApiClient {
  /**
   * Get Metros
   */
  listMetros(params: CallOptions = {}): Promise<models.ListMetroResponse> {
    return this.request<models.ListMetroResponse>(
      {
        method: "GET",
        path: `/v1/metros`,
      },
      params,
    );
  }
}
