// Code generated by openapi-gen; DO NOT EDIT.
//
// Type definitions for the Unikraft Cloud API, generated from the OpenAPI
// specification. These mirror the wire format exactly.

/**
 * AWSConfig contains AWS-specific configuration for node provisioning.
 */

export interface AWSConfig {
  /**
   * The VPC ID where the instance will be launched. If not specified, the
   * default VPC for the region will be used.
   */
  vpc_id?: string;
  /**
   * The subnet ID where the instance will be launched. If not specified,
   * a subnet will be selected from the VPC.
   */
  subnet_id?: string;
  /**
   * Security group IDs to attach to the instance. If not specified, the
   * default security group for the VPC will be used.
   */
  security_group_ids?: string[];
  /**
   * The IAM instance profile ARN or name to attach to the instance.
   */
  iam_instance_profile?: string;
  /**
   * Root EBS volume configuration. If not specified, provider defaults
   * will be used.
   */
  root_volume?: AWSEBSConfig;
  /**
   * Additional EBS volumes to attach to the instance.
   */
  additional_volumes?: AWSEBSConfig[];
  /**
   * Whether to use a dedicated host. Dedicated hosts provide visibility and
   * control over how instances are placed on physical servers.
   */
  dedicated_host: boolean;
  /**
   * Placement group name for the instance. Placement groups influence how
   * instances are placed on underlying hardware.
   */
  placement_group?: string;
  /**
   * The AWS region where the machine is located.
   */
  region: string;
  /**
   * The AWS machine type. This determines the compute resources
   * (CPU, memory, etc.) available on the machine. The valid values depend
   * on the chosen provider.
   */
  machine_type: string;
}

/**
 * AWSEBSConfig defines the configuration for an AWS EBS volume.
 */

export interface AWSEBSConfig {
  /**
   * The device name (e.g., "/dev/sda1", "/dev/xvdf"). Required for
   * additional volumes.
   */
  device_name?: string;
  /**
   * Size of the volume in GiB.
   */
  size_gib: number;
  /**
   * The volume type (gp3, gp2, io1, io2, st1, sc1, standard).
   */
  volume_type: string;
  /**
   * The number of IOPS. Only valid for io1, io2, and gp3 volumes.
   */
  iops?: number;
  /**
   * The throughput in MiB/s. Only valid for gp3 volumes.
   */
  throughput_mibps?: number;
  /**
   * Whether the volume should be encrypted.
   */
  encrypted: boolean;
  /**
   * The KMS key ID for encryption. If encrypted is true and this is not
   * specified, the default EBS encryption key will be used.
   */
  kms_key_id?: string;
  /**
   * Whether to delete the volume when the instance is terminated.
   */
  delete_on_termination: boolean;
}

/**
 * The request message for checking authorization given a request ID.
 */

export interface CheckAuthorizationRequest {
  /**
   * The request ID is a unique identifier for the request.  This is used to
   * track the request in the system and should be provided by the client.
   */
  request_id: string;
}

/**
 * The response message for checking authorization.
 */

export interface CheckAuthorizationResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the response.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data?: CheckAuthorizationResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.  This is the time it took to process
   * the request and generate the response.
   */
  op_time_us: number;
}

export interface CheckAuthorizationResponseData {
  /**
   * The authorization token which can be used to authenticate requests.
   */
  token: string;
  /**
   * The organization name the token is associated with.
   */
  organization_name: string;
  /**
   * The display name of the organization the token is associated with.
   */
  organization_display_name: string;
  /**
   * The global image registry.
   */
  registry: string;
}

/**
 * CloudProvider identifies the cloud infrastructure provider where nodes are
 * provisioned.
 */

export type CloudProvider = "manual" | "aws";

/**
 * CloudProviderConfig contains provider-specific configuration for node
 * provisioning.
 */

export interface CloudProviderConfig {
  /**
   * AWS-specific configuration.
   */
  aws?: AWSConfig;
}

/**
 * Response message for deleting nodes.
 */

export interface DestroyNodeResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the response.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data?: DestroyNodeResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  op_time_us: number;
}

export interface DestroyNodeResponseData {
  /**
   * The deleted nodes (with their final state before deletion).
   */
  nodes?: Node[];
}

/**
 * The response message for getting authorization details.
 */

export interface GetAuthorizationResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the response.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data?: GetAuthorizationResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.  This is the time it took to process
   * the request and generate the response.
   */
  op_time_us: number;
}

export interface GetAuthorizationResponseData {
  /**
   * The organization name the token is associated with.
   */
  organization_name: string;
  /**
   * The display name of the organization the token is associated with.
   */
  organization_display_name: string;
  /**
   * The global image registry.
   */
  registry: string;
}

export interface Image {
  /**
   * The canonical name of the image.
   */
  name: string;
  /**
   * The list of tags for the image.  Only populated when details are requested.
   */
  tags?: ImageTag[];
}

export interface ImageTag {
  /**
   * The tag name.
   */
  name: string;
  /**
   * The digest for the tag.
   */
  digest: string;
  /**
   * The size of the image in bytes.
   */
  size: number;
  /**
   * The push time of the image.
   */
  push_time: string;
}

export interface ListImagesResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the response.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data?: ListImagesResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.  This is the time it took to process
   * the request and generate the response.
   */
  op_time_us: number;
}

export interface ListImagesResponseData {
  /**
   * The list of images.
   */
  images?: Image[];
}

/**
 * Response message for listing machine types.
 */

export interface ListMachineTypesResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the response.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data?: ListMachineTypesResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  op_time_us: number;
}

export interface ListMachineTypesResponseData {
  /**
   * The list of available machine types.
   */
  machine_types?: MachineType[];
}

export interface ListMetroResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the response.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data?: ListMetroResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.  This is the time it took to process
   * the request and generate the response.
   */
  op_time_us: number;
}

export interface ListMetroResponseData {
  /**
   * The list of metros.
   */
  metros?: Metro[];
}

/**
 * Response message for getting nodes.
 */

export interface ListNodesResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the response.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data?: ListNodesResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  op_time_us: number;
}

export interface ListNodesResponseData {
  /**
   * The list of nodes matching the request.
   */
  nodes?: Node[];
  /**
   * Total count of nodes matching the filters (for pagination).
   */
  total_count: number;
}

/**
 * Response message for listing regions.
 */

export interface ListRegionsResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the response.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data?: ListRegionsResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  op_time_us: number;
}

export interface ListRegionsResponseData {
  /**
   * The list of available regions.
   */
  regions?: Region[];
}

/**
 * Information about an available machine type.
 */

export interface MachineType {
  /**
   * The machine type identifier (e.g., "m5.xlarge", "n2-standard-4").
   */
  name: string;
  /**
   * Human-readable description.
   */
  description?: string;
  /**
   * Number of vCPUs.
   */
  vcpus: number;
  /**
   * Memory in MiB.
   */
  memory_mib: number;
  /**
   * Machine category (e.g., "general-purpose", "compute-optimized",
   * "memory-optimized").
   */
  category?: string;
  /**
   * Regions where this machine type is available.
   */
  available_regions?: string[];
  /**
   * Whether this machine type supports nested virtualization.
   */
  nested_virtualization: boolean;
}

export interface Metro {
  /**
   * The UUID of the metro.
   */
  uuid: string;
  /**
   * The API endpoint for the metro.
   */
  endpoint: string;
  /**
   * The name of the metro.
   */
  name: string;
  /**
   * The IATA code of the metro.
   */
  iata_code: string;
  /**
   * The country where the metro is located.
   */
  country: string;
}

/**
 * The operations available on a node's mutable properties.
 */

export type MutableNodeOperation = "set" | "add" | "del";

/**
 * The mutable properties of a node which can be updated.
 */

export type MutableNodeProperty = "tags" | "delete_lock" | "ssh_keys";

/**
 * An identifier for a resource.  Either a name or a UUID.
 */

export interface NameOrUUID {
  /**
   * The UUID of the resource.
   */
  uuid?: string;
  /**
   * The name of the resource.
   */
  name?: string;
}

/**
 * Node represents a physical or virtual compute node provisioned on a
 * cloud provider for use as part of the Unikraft Cloud infrastructure.
 *
 * Node nodes are the underlying compute resources where Unikraft Cloud
 * instances run.  They are provisioned on-demand across multiple cloud
 * providers and managed through a unified API.
 */

export interface Node {
  /**
   * The UUID of the machine.
   *
   * This is a unique identifier for the machine that is generated when the
   * machine is created. The UUID is used to reference the machine in API calls
   * and
   * can be used to identify the machine in all API calls that require a machine
   * identifier.
   */
  uuid: string;
  /**
   * The name of the machine.
   *
   * This is a human-readable name that can be used to identify the machine.
   * The name must be unique within the context of your account. The name can
   * also be used to identify the machine in API calls.
   */
  name: string;
  /**
   * The time the machine was created.
   */
  created_at: string;
  /**
   * The time the machine was last updated.
   */
  updated_at?: string;
  /**
   * The current state of the machine.
   */
  state: NodeState;
  /**
   * An optional message providing additional information about the current
   * state, particularly useful for error states.
   */
  state_message?: string;
  /**
   * The cloud provider where this machine is provisioned.
   */
  cloudprovider?: CloudProvider;
  /**
   * The number of vCPUs available on this machine.
   */
  vcpus: number;
  /**
   * The amount of memory in MiB available on this machine.
   */
  memory_mib: number;
  /**
   * The SSH keys configured for access to this machine.
   */
  ssh_keys?: SSHKey[];
  /**
   * The public IPv4 address of the machine, if assigned.
   */
  public_ipv4?: string;
  /**
   * The public IPv6 address of the machine, if assigned.
   */
  public_ipv6?: string;
  /**
   * The private IPv4 address of the machine within the provider's network.
   */
  private_ipv4?: string;
  /**
   * The Unikraft Cloud metro this machine is associated with.
   */
  metro?: string;
  /**
   * The provider-specific instance ID or resource identifier.
   */
  provider_instance_id?: string;
  /**
   * Provider-specific configuration that was used to provision this node.
   */
  provider_config?: CloudProviderConfig;
  /**
   * User-defined tags for organizing and filtering nodes.
   */
  tags?: Record<string, string>;
  /**
   * The time when the machine became ready (entered READY state).
   */
  ready_at?: string;
  /**
   * The total uptime of the machine in seconds since it became ready.
   */
  uptime_seconds: number;
  /**
   * Whether the machine is protected from deletion. When true, delete operations
   * will fail until this is set to false.
   */
  delete_lock: boolean;
  /**
   * The API endpoint for the node, used to connect to the node's platform SDK.
   */
  api_endpoint?: string;
}

/**
 * The request message for certificate activation.
 */

export interface NodeActivateRequest {
  /**
   * The certificate signing request (CSR) for the license which is base64
   * encoded.
   */
  csr: string;
  /**
   * An opaque secret for first-time activation. On renewal (where the node's
   * public key is already known), this field is omitted and the CSR
   * self-signature is used as proof of key possession.
   */
  secret?: string;
  /**
   * The serial number of the last issued certificate.
   */
  serial?: string;
}

/**
 * The response message for certificate activation.
 */

export interface NodeActivateResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * / An optional message providing additional information about the response.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data?: NodeActivateResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  op_time_us: number;
}

export interface NodeActivateResponseData {
  /**
   * The issued license certificate in base64 URL encoded PEM format.
   */
  license: string;
}

/**
 * The request message for license deactivation. The caller is identified by
 * an HTTP message signature (RFC 9421) made with the node's stable private
 * key, the same mechanism used by the private node-facing APIs (e.g.
 * NodeHeartbeat) -- not by any field in this message.
 */

export interface NodeDeactivateRequest {
  /**
   * The serial number of the last issued certificate.
   */
  serial: string;
}

/**
 * The response message for license deactivation.
 */

export interface NodeDeactivateResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the response.
   */
  message?: string;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  op_time_us: number;
}

/**
 * NodeState defines the provisioning lifecycle state of a machine which will
 * run the Unikraft Cloud Platform.
 */

export type NodeState =
  | "unspecified"
  | "pending"
  | "provisioning"
  | "configuring"
  | "ready"
  | "deprovisioning"
  | "deprovisioned"
  | "error"
  | "maintenance";

/**
 * Request message for creating a new node.
 */

export interface ProvisionNodeRequest {
  /**
   * Optional name for the node. If not provided, a name will be
   * auto-generated.
   */
  name?: string;
  /**
   * The cloud provider where the machine should be provisioned.
   */
  cloudprovider?: CloudProvider;
  /**
   * SSH keys for accessing the node. At least one key is required.
   */
  ssh_keys: SSHKey[];
  /**
   * Optional user-defined tags.
   */
  tags?: Record<string, string>;
  /**
   * Optional provider-specific configuration for advanced customization.
   */
  cloudprovider_config?: CloudProviderConfig;
  /**
   * The Unikraft Cloud metro to associate this machine with.
   */
  metro?: string;
  /**
   * Optional user overrides for platform configuration. Keys should be
   * kebab-case (e.g., "vm-user-min-memory").
   */
  platform_config?: Record<string, string>;
  /**
   * Optional image references to pre-pull on the provisioned machine.
   */
  image_pulls?: string[];
  /**
   * Optional network count override. If not specified, defaults to 1000.
   */
  net_count?: number;
}

/**
 * Response message for creating a node.
 */

export interface ProvisionNodeResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the response.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data?: ProvisionNodeResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  op_time_us: number;
}

export interface ProvisionNodeResponseData {
  /**
   * The created node.
   */
  node: Node;
}

/**
 * Information about an available region.
 */

export interface Region {
  /**
   * The region identifier (e.g., "us-east-1", "us-central1").
   */
  name: string;
  /**
   * The IATA code for the region.
   */
  iata: string;
}

/**
 * The request message for a sign-in request.
 */

export interface RequestSigninRequest {
  /**
   * The hostname is the name of the machine making the request.  This is
   * mandatory as it consitutes a unique identifier for the machine.
   */
  hostname: string;
  /**
   * The operating system of the machine making the request.
   */
  os?: string;
  /**
   * The version of the operating system of the machine making the request, if
   * available.
   *
   * For Android, it's like "10", "11", "12", etc.  For iOS and macOS it's like
   * "15.6.1" or "12.4.0".  For Windows it's like "10.0.19044.1889". For FreeBSD
   * it's like "12.3-STABLE".  For Linux, this is simply the kernel version on
   * Linux, like "5.10.0-17-amd64".
   */
  os_version?: string;
  /**
   * A best-effort whether the client is running in a container.
   */
  container?: boolean;
  /**
   * The OS distribution, if known.  E.g. "debian", "ubuntu", "nixos", ...
   */
  distro?: string;
  /**
   * The OS distribution version if known.  E.g. "20.04", ...
   */
  distro_version?: string;
  /**
   * TThe OS distribution codename if known.  E.g. "jammy", "bullseye", ...
   */
  distro_codename?: string;
  /**
   * The CLI version is the version of the Unikraft CLI that is making the
   * request.
   */
  cli_version?: string;
  /**
   * If available, the GOARCH value (of the built binary).
   */
  goarch?: string;
  /**
   * If available, the GOOS value (of the built binary)
   */
  goos?: string;
  /**
   * if available, the Go version binary was built with.
   */
  go_version?: string;
}

/**
 * The response message for a sign-in request.
 */

export interface RequestSigninResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the response.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data?: RequestSigninResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.  This is the time it took to process
   * the request and generate the response.
   */
  op_time_us: number;
}

export interface RequestSigninResponseData {
  /**
   * The full URL which can be used to remotely confirm the signin.
   */
  authorization_url: string;
  /**
   * A unique identifier for the request.  This can be used to track the
   * request in the system.
   */
  request_id: string;
}

/**
 * The error response message for an API request.
 */

export interface ResponseError {
  /**
   * The HTTP status code of the error.
   */
  status: number;
}

/**
 * The response status of an API request.
 */

export type ResponseStatus = "success" | "error" | "partial_success";

/**
 * SSHKey represents an SSH public key for authentication.
 */

export interface SSHKey {
  /**
   * A name or label for this SSH key.
   */
  name: string;
  /**
   * The SSH public key in OpenSSH format (e.g., "ssh-rsa AAAA... user@host"
   * or "ssh-ed25519 AAAA... user@host").
   */
  public_key: string;
}

/**
 * UpdateNodePayload contains the changes to apply to a node.
 */

export interface UpdateNodePayload {
  /**
   * The property to update.
   */
  property: MutableNodeProperty;
  /**
   * The operation to perform on the property.
   */
  operation: MutableNodeOperation;
  /**
   * The value for the update operation. The type depends on the property:
   * - TAGS: google.protobuf.Struct with key-value pairs
   * - DELETE_LOCK: google.protobuf.Value with boolean
   * - SSH_KEYS: google.protobuf.ListValue with SSHKey objects
   */
  value?: string;
}

/**
 * Response message for updating nodes.
 */

export interface UpdateNodesResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the response.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data?: UpdateNodesResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  op_time_us: number;
}

export interface UpdateNodesResponseData {
  /**
   * The updated nodes.
   */
  nodes?: Node[];
}

/**
 * Response message for wait operations.
 */

export interface WaitNodesResponse {
  /**
   * The status of the response.
   */
  status: ResponseStatus;
  /**
   * An optional message providing additional information about the response.
   */
  message?: string;
  /**
   * The response data for this request.
   */
  data?: WaitNodesResponseData;
  /**
   * A list of errors which may have occurred during the request.
   */
  errors?: ResponseError[];
  /**
   * The operation time in microseconds.
   */
  op_time_us: number;
}

export interface WaitNodesResponseData {
  /**
   * The nodes after reaching the desired state.
   */
  nodes?: Node[];
}
