// Code generated by openapi-gen; DO NOT EDIT.
import { ApiClient, type CallOptions } from "../../core/http.js";
import type * as models from "./models.gen.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `NodeActivationService` resource. Methods return the raw response envelope.
 */
export class NodeActivationServiceApi extends ApiClient {
  /**
   * Activates a new node, or renews an existing node's license. For first-time
   * activation, a secret must be provided. For renewal, the CSR self-signature
   * is used as proof of key possession and the secret is omitted.
   */
  nodeActivate(
    params: {
      body: models.NodeActivateRequest;
    } & CallOptions,
  ): Promise<models.NodeActivateResponse> {
    return this.request<models.NodeActivateResponse>(
      {
        method: "POST",
        path: `/v1/nodes/activate`,
        body: params.body,
      },
      params,
    );
  }
}
