// Code generated by openapi-gen; DO NOT EDIT.
import { ApiClient, type CallOptions } from "../../core/http.js";
import type * as models from "./models.gen.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `NodeActivationService` resource. Methods return the raw response envelope.
 */
export class NodeActivationServiceApi extends ApiClient {
  /**
   * Activates a new node, or renews an existing node's license. For first-time
   * activation, a secret must be provided. For renewal, the CSR self-signature
   * is used as proof of key possession and the secret is omitted.
   *
   * A renewal request may optionally also carry an HTTP message signature
   * (RFC 9421) made with the node's current stable private key. When present
   * and valid, it authorizes the CSR's public key to become the node's new
   * stable identity even if it differs from the current one -- i.e. key
   * rotation: prove who you are with the old key, then switch to the new one
   * named in the CSR.
   */
  nodeActivate(
    params: {
      body: models.NodeActivateRequest;
    } & CallOptions,
  ): Promise<models.NodeActivateResponse> {
    return this.request<models.NodeActivateResponse>(
      {
        method: "POST",
        path: `/v1/nodes/activate`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Deactivates a node's license so it can no longer renew. The node's
   * issued certificate remains valid until it naturally expires -- this
   * only prevents renewal. The request must carry an HTTP message signature
   * (RFC 9421) made with the node's stable private key; the node is
   * identified by the signature, the same mechanism used by the private
   * node-facing APIs (e.g. NodeHeartbeat).
   */
  nodeDeactivate(
    params: {
      body: models.NodeDeactivateRequest;
    } & CallOptions,
  ): Promise<models.NodeDeactivateResponse> {
    return this.request<models.NodeDeactivateResponse>(
      {
        method: "POST",
        path: `/v1/nodes/deactivate`,
        body: params.body,
      },
      params,
    );
  }
}
