// Code generated by openapi-gen; DO NOT EDIT.
import { ApiClient, type CallOptions } from "../../core/http.js";
import type * as models from "./models.gen.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `NodeService` resource. Methods return the raw response envelope.
 */
export class NodeServiceApi extends ApiClient {
  /**
   * Delete Node Nodes
   */
  destroyNode(
    params: {
      force?: boolean;
      body: models.NameOrUUID[];
    } & CallOptions,
  ): Promise<models.DestroyNodeResponse> {
    return this.request<models.DestroyNodeResponse>(
      {
        method: "DELETE",
        path: `/v1/nodes`,
        query: {
          force: params["force"],
        },
        body: params.body,
      },
      params,
    );
  }

  /**
   * Delete Node Node by UUID
   */
  destroyNodeByUuid(
    uuid: string,
    params: {
      force?: boolean;
    } & CallOptions = {},
  ): Promise<models.DestroyNodeResponse> {
    return this.request<models.DestroyNodeResponse>(
      {
        method: "DELETE",
        path: `/v1/nodes/${uuid}`,
        query: {
          force: params["force"],
        },
      },
      params,
    );
  }

  /**
   * Get Node Node by UUID
   */
  getNodeByUuid(uuid: string, params: CallOptions = {}): Promise<models.ListNodesResponse> {
    return this.request<models.ListNodesResponse>(
      {
        method: "GET",
        path: `/v1/nodes/${uuid}`,
      },
      params,
    );
  }

  /**
   * List Machine Types
   */
  listMachineTypes(
    cloudprovider: models.CloudProvider,
    params: {
      region?: string;
    } & CallOptions = {},
  ): Promise<models.ListMachineTypesResponse> {
    return this.request<models.ListMachineTypesResponse>(
      {
        method: "GET",
        path: `/v1/nodes/providers/${cloudprovider}/types`,
        query: {
          region: params["region"],
        },
      },
      params,
    );
  }

  /**
   * List Node Nodes
   */
  listNodes(
    params: {
      uuid?: string[];
      name?: string[];
      cloudprovider?: models.CloudProvider;
      state?: models.NodeState;
      metro?: string;
      limit?: number;
      offset?: number;
    } & CallOptions = {},
  ): Promise<models.ListNodesResponse> {
    return this.request<models.ListNodesResponse>(
      {
        method: "GET",
        path: `/v1/nodes`,
        query: {
          uuid: params["uuid"],
          name: params["name"],
          cloudprovider: params["cloudprovider"],
          state: params["state"],
          metro: params["metro"],
          limit: params["limit"],
          offset: params["offset"],
        },
      },
      params,
    );
  }

  /**
   * List Regions
   */
  listRegions(
    cloudprovider: models.CloudProvider,
    params: CallOptions = {},
  ): Promise<models.ListRegionsResponse> {
    return this.request<models.ListRegionsResponse>(
      {
        method: "GET",
        path: `/v1/nodes/providers/${cloudprovider}/regions`,
      },
      params,
    );
  }

  /**
   * Create Node Node
   */
  provisionNode(
    params: {
      body: models.ProvisionNodeRequest;
    } & CallOptions,
  ): Promise<models.ProvisionNodeResponse> {
    return this.request<models.ProvisionNodeResponse>(
      {
        method: "POST",
        path: `/v1/nodes`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Update Node Node by UUID
   */
  updateNodeByUuid(
    uuid: string,
    params: {
      body: models.UpdateNodePayload[];
    } & CallOptions,
  ): Promise<models.UpdateNodesResponse> {
    return this.request<models.UpdateNodesResponse>(
      {
        method: "PATCH",
        path: `/v1/nodes/${uuid}`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Update Node Nodes
   */
  updateNodes(
    params: {
      property?: models.MutableNodeProperty[];
      operation?: models.MutableNodeOperation[];
      value?: string[];
      body: models.NameOrUUID[];
    } & CallOptions,
  ): Promise<models.UpdateNodesResponse> {
    return this.request<models.UpdateNodesResponse>(
      {
        method: "PATCH",
        path: `/v1/nodes`,
        query: {
          property: params["property"],
          operation: params["operation"],
          value: params["value"],
        },
        body: params.body,
      },
      params,
    );
  }

  /**
   * Wait for Node Node State by UUID
   */
  waitNodeByUuid(
    uuid: string,
    params: {
      states?: models.NodeState[];
      timeout_ms?: number;
    } & CallOptions = {},
  ): Promise<models.WaitNodesResponse> {
    return this.request<models.WaitNodesResponse>(
      {
        method: "GET",
        path: `/v1/nodes/${uuid}/wait`,
        query: {
          states: params["states"],
          timeout_ms: params["timeout_ms"],
        },
      },
      params,
    );
  }

  /**
   * Wait for Node Nodes States
   */
  waitNodes(
    params: {
      uuid?: string[];
      name?: string[];
      states?: models.NodeState[];
      timeout_ms?: number;
    } & CallOptions = {},
  ): Promise<models.WaitNodesResponse> {
    return this.request<models.WaitNodesResponse>(
      {
        method: "GET",
        path: `/v1/nodes/wait`,
        query: {
          uuid: params["uuid"],
          name: params["name"],
          states: params["states"],
          timeout_ms: params["timeout_ms"],
        },
      },
      params,
    );
  }
}
