// Code generated by openapi-gen; DO NOT EDIT.
import { ApiClient, type CallOptions } from "../../core/http.js";
import type * as models from "./models.gen.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `audit` resource. Methods return the raw response envelope.
 */
export class AuditApi extends ApiClient {
  /**
   * Subscribe to Audit Events
   */
  subscribeAuditEvents(
    params: {
      events?: models.AuditEventType[];
      uuid?: string[];
      tags?: string[];
    } & CallOptions = {},
  ): AsyncGenerator<models.AuditEvent, void, void> {
    return this.stream<models.AuditEvent>(
      {
        method: "GET",
        path: `/v1/audit`,
        query: {
          events: params["events"],
          uuid: params["uuid"],
          tags: params["tags"],
        },
      },
      params,
    );
  }
}
