// Code generated by openapi-gen; DO NOT EDIT.
import { ApiClient, type CallOptions } from "../../core/http.js";
import type * as models from "./models.gen.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `Autoscale` resource. Methods return the raw response envelope.
 */
export class AutoscaleApi extends ApiClient {
  /**
   * Create Autoscale Configuration by Service Group UUID
   */
  createAutoscaleConfigurationByServiceGroupUuid(
    uuid: string,
    params: {
      body: models.CreateAutoscaleConfigurationByServiceGroupUUIDRequest;
    } & CallOptions,
  ): Promise<models.CreateAutoscaleConfigurationsResponse> {
    return this.request<models.CreateAutoscaleConfigurationsResponse>(
      {
        method: "POST",
        path: `/v1/services/${uuid}/autoscale`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Create Autoscale Configuration Policy
   */
  createAutoscaleConfigurationPolicy(
    uuid: string,
    params: {
      body: models.CreateAutoscaleConfigurationPolicyRequest;
    } & CallOptions,
  ): Promise<models.CreateAutoscaleConfigurationPolicyResponse> {
    return this.request<models.CreateAutoscaleConfigurationPolicyResponse>(
      {
        method: "POST",
        path: `/v1/services/${uuid}/autoscale/policies`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Create Autoscale Configurations
   */
  createAutoscaleConfigurations(
    params: {
      body: models.CreateAutoscaleConfigurationsRequestConfiguration[];
    } & CallOptions,
  ): Promise<models.CreateAutoscaleConfigurationsResponse> {
    return this.request<models.CreateAutoscaleConfigurationsResponse>(
      {
        method: "POST",
        path: `/v1/services/autoscale`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Delete Autoscale Configuration Policies
   */
  deleteAutoscaleConfigurationPolicies(
    uuid: string,
    params: {
      body: models.DeletePolicyRequest;
    } & CallOptions,
  ): Promise<models.DeleteAutoscaleConfigurationPolicyResponse> {
    return this.request<models.DeleteAutoscaleConfigurationPolicyResponse>(
      {
        method: "DELETE",
        path: `/v1/services/${uuid}/autoscale/policies`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Delete Autoscale Configuration Policy by Name
   */
  deleteAutoscaleConfigurationPolicyByName(
    uuid: string,
    name: string,
    params: CallOptions = {},
  ): Promise<models.DeleteAutoscaleConfigurationPolicyResponse> {
    return this.request<models.DeleteAutoscaleConfigurationPolicyResponse>(
      {
        method: "DELETE",
        path: `/v1/services/${uuid}/autoscale/policies/${name}`,
      },
      params,
    );
  }

  /**
   * Delete Autoscale Configurations
   */
  deleteAutoscaleConfigurations(
    params: {
      body: models.NameOrUUID[];
    } & CallOptions,
  ): Promise<models.DeleteAutoscaleConfigurationsResponse> {
    return this.request<models.DeleteAutoscaleConfigurationsResponse>(
      {
        method: "DELETE",
        path: `/v1/services/autoscale`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Delete Autoscale Configurations by Service Group UUID
   */
  deleteAutoscaleConfigurationsByServiceGroupUuid(
    uuid: string,
    params: CallOptions = {},
  ): Promise<models.DeleteAutoscaleConfigurationsResponse> {
    return this.request<models.DeleteAutoscaleConfigurationsResponse>(
      {
        method: "DELETE",
        path: `/v1/services/${uuid}/autoscale`,
      },
      params,
    );
  }

  /**
   * List Autoscale Configuration Policies
   */
  getAutoscaleConfigurationPolicies(
    uuid: string,
    params: CallOptions = {},
  ): Promise<models.GetAutoscaleConfigurationPolicyResponse> {
    return this.request<models.GetAutoscaleConfigurationPolicyResponse>(
      {
        method: "GET",
        path: `/v1/services/${uuid}/autoscale/policies`,
      },
      params,
    );
  }

  /**
   * Get Autoscale Configuration Policy by Name
   */
  getAutoscaleConfigurationPolicyByName(
    uuid: string,
    name: string,
    params: CallOptions = {},
  ): Promise<models.GetAutoscaleConfigurationPolicyResponse> {
    return this.request<models.GetAutoscaleConfigurationPolicyResponse>(
      {
        method: "GET",
        path: `/v1/services/${uuid}/autoscale/policies/${name}`,
      },
      params,
    );
  }

  /**
   * List Autoscale Configurations
   */
  getAutoscaleConfigurations(
    params: {
      uuid?: string[];
      name?: string[];
    } & CallOptions = {},
  ): Promise<models.GetAutoscaleConfigurationsResponse> {
    return this.request<models.GetAutoscaleConfigurationsResponse>(
      {
        method: "GET",
        path: `/v1/services/autoscale`,
        query: {
          uuid: params["uuid"],
          name: params["name"],
        },
      },
      params,
    );
  }

  /**
   * Get Autoscale Configurations by Service Group UUID
   */
  getAutoscaleConfigurationsByServiceGroupUuid(
    uuid: string,
    params: CallOptions = {},
  ): Promise<models.GetAutoscaleConfigurationsResponse> {
    return this.request<models.GetAutoscaleConfigurationsResponse>(
      {
        method: "GET",
        path: `/v1/services/${uuid}/autoscale`,
      },
      params,
    );
  }
}
