// Code generated by openapi-gen; DO NOT EDIT.
import { ApiClient, type CallOptions } from "../../core/http.js";
import type * as models from "./models.gen.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `Certificates` resource. Methods return the raw response envelope.
 */
export class CertificatesApi extends ApiClient {
  /**
   * Create Certificate
   */
  createCertificate(
    params: {
      body: models.CreateCertificateRequest;
    } & CallOptions,
  ): Promise<models.CreateCertificateResponse> {
    return this.request<models.CreateCertificateResponse>(
      {
        method: "POST",
        path: `/v1/certificates`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Delete Certificate by UUID
   */
  deleteCertificateByUuid(
    uuid: string,
    params: CallOptions = {},
  ): Promise<models.DeleteCertificatesResponse> {
    return this.request<models.DeleteCertificatesResponse>(
      {
        method: "DELETE",
        path: `/v1/certificates/${uuid}`,
      },
      params,
    );
  }

  /**
   * Delete Certificates
   */
  deleteCertificates(
    params: {
      body: models.NameOrUUID[];
    } & CallOptions,
  ): Promise<models.DeleteCertificatesResponse> {
    return this.request<models.DeleteCertificatesResponse>(
      {
        method: "DELETE",
        path: `/v1/certificates`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Get Certificate by UUID
   */
  getCertificateByUuid(
    uuid: string,
    params: CallOptions = {},
  ): Promise<models.GetCertificatesResponse> {
    return this.request<models.GetCertificatesResponse>(
      {
        method: "GET",
        path: `/v1/certificates/${uuid}`,
      },
      params,
    );
  }

  /**
   * List Certificates
   */
  getCertificates(
    params: {
      uuid?: string[];
      name?: string[];
      details?: boolean;
      count?: number;
      from?: string;
      order?: models.PaginationOrder;
      sortby?: models.PaginationSortBy;
    } & CallOptions = {},
  ): Promise<models.GetCertificatesResponse> {
    return this.request<models.GetCertificatesResponse>(
      {
        method: "GET",
        path: `/v1/certificates`,
        query: {
          uuid: params["uuid"],
          name: params["name"],
          details: params["details"],
          count: params["count"],
          from: params["from"],
          order: params["order"],
          sortby: params["sortby"],
        },
      },
      params,
    );
  }

  /**
   * Update Certificate by UUID
   */
  updateCertificateByUuid(
    uuid: string,
    params: {
      body: models.UpdateCertificateByUUIDRequestBody;
    } & CallOptions,
  ): Promise<models.UpdateCertificatesResponse> {
    return this.request<models.UpdateCertificatesResponse>(
      {
        method: "PUT",
        path: `/v1/certificates/${uuid}`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Update Certificates
   */
  updateCertificates(
    params: {
      body: models.UpdateCertificatesRequestItem[];
    } & CallOptions,
  ): Promise<models.UpdateCertificatesResponse> {
    return this.request<models.UpdateCertificatesResponse>(
      {
        method: "PUT",
        path: `/v1/certificates`,
        body: params.body,
      },
      params,
    );
  }
}
