// Code generated by openapi-gen; DO NOT EDIT.
import { ApiClient, type CallOptions } from "../../core/http.js";
import type * as models from "./models.gen.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `Images` resource. Methods return the raw response envelope.
 */
export class ImagesApi extends ApiClient {
  /**
   * Get Images in Store
   */
  getImageStore(
    params: {
      digest?: string;
      tag?: string;
    } & CallOptions = {},
  ): Promise<models.GetImagesResponse> {
    return this.request<models.GetImagesResponse>(
      {
        method: "GET",
        path: `/v1/image-store`,
        query: {
          digest: params["digest"],
          tag: params["tag"],
        },
      },
      params,
    );
  }

  /**
   * Get Images
   */
  getImages(
    params: {
      digest?: string;
      tag?: string;
    } & CallOptions = {},
  ): Promise<models.GetImagesResponse> {
    return this.request<models.GetImagesResponse>(
      {
        method: "GET",
        path: `/v1/images`,
        query: {
          digest: params["digest"],
          tag: params["tag"],
        },
      },
      params,
    );
  }
}
