// Code generated by openapi-gen; DO NOT EDIT.
import { ApiClient, type CallOptions } from "../../core/http.js";
import type * as models from "./models.gen.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `Instances` resource. Methods return the raw response envelope.
 */
export class InstancesApi extends ApiClient {
  /**
   * Create checkpoint instances
   */
  createCheckpointInstances(
    params: {
      body: models.CreateCheckpointInstancesRequestItem[];
    } & CallOptions,
  ): Promise<models.CreateCheckpointInstancesResponse> {
    return this.request<models.CreateCheckpointInstancesResponse>(
      {
        method: "POST",
        path: `/v1/instances/checkpoints`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Create Instance
   */
  createInstance(
    params: {
      body: models.CreateInstanceRequest;
    } & CallOptions,
  ): Promise<models.CreateInstanceResponse> {
    return this.request<models.CreateInstanceResponse>(
      {
        method: "POST",
        path: `/v1/instances`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Create template instances from Instances
   */
  createTemplateInstances(
    params: {
      body: models.CreateTemplateInstancesRequestItem[];
    } & CallOptions,
  ): Promise<models.CreateTemplateInstancesResponse> {
    return this.request<models.CreateTemplateInstancesResponse>(
      {
        method: "POST",
        path: `/v1/instances/templates`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Delete checkpoint instance by UUID
   */
  deleteCheckpointInstanceByUuid(
    uuid: string,
    params: CallOptions = {},
  ): Promise<models.DeleteCheckpointInstancesResponse> {
    return this.request<models.DeleteCheckpointInstancesResponse>(
      {
        method: "DELETE",
        path: `/v1/instances/checkpoints/${uuid}`,
      },
      params,
    );
  }

  /**
   * Delete checkpoint instances
   */
  deleteCheckpointInstances(
    params: {
      body: models.NameOrUUID[];
    } & CallOptions,
  ): Promise<models.DeleteCheckpointInstancesResponse> {
    return this.request<models.DeleteCheckpointInstancesResponse>(
      {
        method: "DELETE",
        path: `/v1/instances/checkpoints`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Delete Instance by UUID
   */
  deleteInstanceByUuid(
    uuid: string,
    params: {
      body?: models.DeleteInstanceByUUIDRequestBody;
    } & CallOptions = {},
  ): Promise<models.DeleteInstancesResponse> {
    return this.request<models.DeleteInstancesResponse>(
      {
        method: "DELETE",
        path: `/v1/instances/${uuid}`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Delete Instances
   */
  deleteInstances(
    params: {
      body: models.DeleteInstanceRequestItem[];
    } & CallOptions,
  ): Promise<models.DeleteInstancesResponse> {
    return this.request<models.DeleteInstancesResponse>(
      {
        method: "DELETE",
        path: `/v1/instances`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Delete template instance by UUID
   */
  deleteTemplateInstanceByUuid(
    uuid: string,
    params: CallOptions = {},
  ): Promise<models.DeleteTemplateInstancesResponse> {
    return this.request<models.DeleteTemplateInstancesResponse>(
      {
        method: "DELETE",
        path: `/v1/instances/templates/${uuid}`,
      },
      params,
    );
  }

  /**
   * Delete template instances
   */
  deleteTemplateInstances(
    params: {
      body: models.NameOrUUID[];
    } & CallOptions,
  ): Promise<models.DeleteTemplateInstancesResponse> {
    return this.request<models.DeleteTemplateInstancesResponse>(
      {
        method: "DELETE",
        path: `/v1/instances/templates`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Get checkpoint history
   */
  getCheckpointHistory(
    params: {
      uuid?: string[];
      name?: string[];
    } & CallOptions = {},
  ): Promise<models.GetCheckpointHistoryResponse> {
    return this.request<models.GetCheckpointHistoryResponse>(
      {
        method: "GET",
        path: `/v1/instances/checkpoints/history`,
        query: {
          uuid: params["uuid"],
          name: params["name"],
        },
      },
      params,
    );
  }

  /**
   * Get checkpoint history by UUID
   */
  getCheckpointHistoryByUuid(
    uuid: string,
    params: CallOptions = {},
  ): Promise<models.GetCheckpointHistoryResponse> {
    return this.request<models.GetCheckpointHistoryResponse>(
      {
        method: "GET",
        path: `/v1/instances/checkpoints/${uuid}/history`,
      },
      params,
    );
  }

  /**
   * Get checkpoint instance by UUID
   */
  getCheckpointInstanceByUuid(
    uuid: string,
    params: {
      details?: boolean;
    } & CallOptions = {},
  ): Promise<models.GetCheckpointInstancesResponse> {
    return this.request<models.GetCheckpointInstancesResponse>(
      {
        method: "GET",
        path: `/v1/instances/checkpoints/${uuid}`,
        query: {
          details: params["details"],
        },
      },
      params,
    );
  }

  /**
   * List checkpoint instances
   */
  getCheckpointInstances(
    params: {
      uuid?: string[];
      name?: string[];
      details?: boolean;
      count?: number;
      tags?: string[];
      from?: string;
      order?: models.PaginationOrder;
      sortby?: models.PaginationSortBy;
    } & CallOptions = {},
  ): Promise<models.GetCheckpointInstancesResponse> {
    return this.request<models.GetCheckpointInstancesResponse>(
      {
        method: "GET",
        path: `/v1/instances/checkpoints`,
        query: {
          uuid: params["uuid"],
          name: params["name"],
          details: params["details"],
          count: params["count"],
          tags: params["tags"],
          from: params["from"],
          order: params["order"],
          sortby: params["sortby"],
        },
      },
      params,
    );
  }

  /**
   * Get Instance by UUID
   */
  getInstanceByUuid(
    uuid: string,
    params: {
      details?: boolean;
    } & CallOptions = {},
  ): Promise<models.GetInstancesResponse> {
    return this.request<models.GetInstancesResponse>(
      {
        method: "GET",
        path: `/v1/instances/${uuid}`,
        query: {
          details: params["details"],
        },
      },
      params,
    );
  }

  /**
   * Get instances checkpoint history
   */
  getInstanceHistory(
    params: {
      uuid?: string[];
      name?: string[];
    } & CallOptions = {},
  ): Promise<models.GetCheckpointHistoryResponse> {
    return this.request<models.GetCheckpointHistoryResponse>(
      {
        method: "GET",
        path: `/v1/instances/history`,
        query: {
          uuid: params["uuid"],
          name: params["name"],
        },
      },
      params,
    );
  }

  /**
   * Get instance checkpoint history by UUID
   */
  getInstanceHistoryByUuid(
    uuid: string,
    params: CallOptions = {},
  ): Promise<models.GetCheckpointHistoryResponse> {
    return this.request<models.GetCheckpointHistoryResponse>(
      {
        method: "GET",
        path: `/v1/instances/${uuid}/history`,
      },
      params,
    );
  }

  /**
   * Get Instances Logs
   */
  getInstanceLogs(
    params: {
      uuid?: string[];
      name?: string[];
      offset?: number[];
      limit?: number[];
    } & CallOptions = {},
  ): Promise<models.GetInstancesLogsResponse> {
    return this.request<models.GetInstancesLogsResponse>(
      {
        method: "GET",
        path: `/v1/instances/log`,
        query: {
          uuid: params["uuid"],
          name: params["name"],
          offset: params["offset"],
          limit: params["limit"],
        },
      },
      params,
    );
  }

  /**
   * Get Instance Logs by UUID
   */
  getInstanceLogsByUuid(
    uuid: string,
    params: CallOptions = {},
  ): Promise<models.GetInstancesLogsResponse> {
    return this.request<models.GetInstancesLogsResponse>(
      {
        method: "GET",
        path: `/v1/instances/${uuid}/log`,
      },
      params,
    );
  }

  /**
   * Get Instances Metrics
   */
  getInstanceMetrics(
    params: {
      uuid?: string[];
      name?: string[];
    } & CallOptions = {},
  ): Promise<models.GetInstancesMetricsResponse> {
    return this.request<models.GetInstancesMetricsResponse>(
      {
        method: "GET",
        path: `/v1/instances/metrics`,
        query: {
          uuid: params["uuid"],
          name: params["name"],
        },
      },
      params,
    );
  }

  /**
   * Get Instance Metrics by UUID
   */
  getInstanceMetricsByUuid(
    uuid: string,
    params: CallOptions = {},
  ): Promise<models.GetInstancesMetricsResponse> {
    return this.request<models.GetInstancesMetricsResponse>(
      {
        method: "GET",
        path: `/v1/instances/${uuid}/metrics`,
      },
      params,
    );
  }

  /**
   * List Instances
   */
  getInstances(
    params: {
      uuid?: string[];
      name?: string[];
      details?: boolean;
      count?: number;
      from?: string;
      tags?: string[];
      order?: models.PaginationOrder;
      sortby?: models.PaginationSortBy;
    } & CallOptions = {},
  ): Promise<models.GetInstancesResponse> {
    return this.request<models.GetInstancesResponse>(
      {
        method: "GET",
        path: `/v1/instances`,
        query: {
          uuid: params["uuid"],
          name: params["name"],
          details: params["details"],
          count: params["count"],
          from: params["from"],
          tags: params["tags"],
          order: params["order"],
          sortby: params["sortby"],
        },
      },
      params,
    );
  }

  /**
   * Get template instance by UUID
   */
  getTemplateInstanceByUuid(
    uuid: string,
    params: {
      details?: boolean;
    } & CallOptions = {},
  ): Promise<models.GetTemplateInstancesResponse> {
    return this.request<models.GetTemplateInstancesResponse>(
      {
        method: "GET",
        path: `/v1/instances/templates/${uuid}`,
        query: {
          details: params["details"],
        },
      },
      params,
    );
  }

  /**
   * List template instances
   */
  getTemplateInstances(
    params: {
      uuid?: string[];
      name?: string[];
      details?: boolean;
      count?: number;
      tags?: string[];
      from?: string;
      order?: models.PaginationOrder;
      sortby?: models.PaginationSortBy;
    } & CallOptions = {},
  ): Promise<models.GetTemplateInstancesResponse> {
    return this.request<models.GetTemplateInstancesResponse>(
      {
        method: "GET",
        path: `/v1/instances/templates`,
        query: {
          uuid: params["uuid"],
          name: params["name"],
          details: params["details"],
          count: params["count"],
          tags: params["tags"],
          from: params["from"],
          order: params["order"],
          sortby: params["sortby"],
        },
      },
      params,
    );
  }

  /**
   * Start Instance by UUID
   */
  startInstanceByUuid(
    uuid: string,
    params: {
      body: models.StartInstanceByUUIDRequestBody;
    } & CallOptions,
  ): Promise<models.StartInstancesResponse> {
    return this.request<models.StartInstancesResponse>(
      {
        method: "PUT",
        path: `/v1/instances/${uuid}/start`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Start Instances
   */
  startInstances(
    params: {
      body: models.StartInstancesRequestItem[];
    } & CallOptions,
  ): Promise<models.StartInstancesResponse> {
    return this.request<models.StartInstancesResponse>(
      {
        method: "PUT",
        path: `/v1/instances/start`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Stop Instance by UUID
   */
  stopInstanceByUuid(
    uuid: string,
    params: {
      body: models.StopInstanceByUUIDRequestBody;
    } & CallOptions,
  ): Promise<models.StopInstancesResponse> {
    return this.request<models.StopInstancesResponse>(
      {
        method: "PUT",
        path: `/v1/instances/${uuid}/stop`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Stop Instances
   */
  stopInstances(
    params: {
      body: models.StopInstancesRequestItem[];
    } & CallOptions,
  ): Promise<models.StopInstancesResponse> {
    return this.request<models.StopInstancesResponse>(
      {
        method: "PUT",
        path: `/v1/instances/stop`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Suspend Instance by UUID
   */
  suspendInstanceByUuid(
    uuid: string,
    params: {
      body: models.SuspendInstanceByUUIDRequestBody;
    } & CallOptions,
  ): Promise<models.SuspendInstancesResponse> {
    return this.request<models.SuspendInstancesResponse>(
      {
        method: "PUT",
        path: `/v1/instances/${uuid}/suspend`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Suspend Instances
   */
  suspendInstances(
    params: {
      body: models.SuspendInstancesRequestItem[];
    } & CallOptions,
  ): Promise<models.SuspendInstancesResponse> {
    return this.request<models.SuspendInstancesResponse>(
      {
        method: "PUT",
        path: `/v1/instances/suspend`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Update checkpoint instance by UUID
   */
  updateCheckpointInstanceByUuid(
    uuid: string,
    params: {
      body: models.UpdateCheckpointInstanceByUUIDRequestBody;
    } & CallOptions,
  ): Promise<models.UpdateCheckpointInstancesResponse> {
    return this.request<models.UpdateCheckpointInstancesResponse>(
      {
        method: "PATCH",
        path: `/v1/instances/checkpoints/${uuid}`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Update checkpoint instances
   */
  updateCheckpointInstances(
    params: {
      body: models.UpdateCheckpointInstancesRequestItem[];
    } & CallOptions,
  ): Promise<models.UpdateCheckpointInstancesResponse> {
    return this.request<models.UpdateCheckpointInstancesResponse>(
      {
        method: "PATCH",
        path: `/v1/instances/checkpoints`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Update Instance by UUID
   */
  updateInstanceByUuid(
    uuid: string,
    params: {
      body: models.UpdateInstanceByUUIDRequestBody;
    } & CallOptions,
  ): Promise<models.UpdateInstancesResponse> {
    return this.request<models.UpdateInstancesResponse>(
      {
        method: "PATCH",
        path: `/v1/instances/${uuid}`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Update Instances
   */
  updateInstances(
    params: {
      body: models.UpdateInstancesRequestItem[];
    } & CallOptions,
  ): Promise<models.UpdateInstancesResponse> {
    return this.request<models.UpdateInstancesResponse>(
      {
        method: "PATCH",
        path: `/v1/instances`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Update template instance by UUID
   */
  updateTemplateInstanceByUuid(
    uuid: string,
    params: {
      body: models.UpdateTemplateInstanceByUUIDRequestBody;
    } & CallOptions,
  ): Promise<models.UpdateTemplateInstancesResponse> {
    return this.request<models.UpdateTemplateInstancesResponse>(
      {
        method: "PATCH",
        path: `/v1/instances/templates/${uuid}`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Update template instances
   */
  updateTemplateInstances(
    params: {
      body: models.UpdateTemplateInstancesRequestItem[];
    } & CallOptions,
  ): Promise<models.UpdateTemplateInstancesResponse> {
    return this.request<models.UpdateTemplateInstancesResponse>(
      {
        method: "PATCH",
        path: `/v1/instances/templates`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Wait for Instance State by UUID
   */
  waitInstanceByUuid(
    uuid: string,
    params: CallOptions = {},
  ): Promise<models.WaitInstancesResponse> {
    return this.request<models.WaitInstancesResponse>(
      {
        method: "GET",
        path: `/v1/instances/${uuid}/wait`,
      },
      params,
    );
  }

  /**
   * Wait for Instances States
   */
  waitInstances(
    params: {
      uuid?: string[];
      name?: string[];
      state?: models.InstanceState[];
      timeout_ms?: number[];
      timeout_s?: number[];
    } & CallOptions = {},
  ): Promise<models.WaitInstancesResponse> {
    return this.request<models.WaitInstancesResponse>(
      {
        method: "GET",
        path: `/v1/instances/wait`,
        query: {
          uuid: params["uuid"],
          name: params["name"],
          state: params["state"],
          timeout_ms: params["timeout_ms"],
          timeout_s: params["timeout_s"],
        },
      },
      params,
    );
  }
}
