// Code generated by openapi-gen; DO NOT EDIT.
import { ApiClient, type CallOptions } from "../../core/http.js";
import type * as models from "./models.gen.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `Node` resource. Methods return the raw response envelope.
 */
export class NodeApi extends ApiClient {
  /**
   * Health Check
   */
  healthz(params: CallOptions = {}): Promise<models.HealthzResponse> {
    return this.request<models.HealthzResponse>(
      {
        method: "GET",
        path: `/v1/healthz`,
      },
      params,
    );
  }
}
