// Code generated by openapi-gen; DO NOT EDIT.
import { ApiClient, type CallOptions } from "../../core/http.js";
import type * as models from "./models.gen.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `ServiceGroups` resource. Methods return the raw response envelope.
 */
export class ServiceGroupsApi extends ApiClient {
  /**
   * Create Service Group
   */
  createServiceGroup(
    params: {
      body: models.CreateServiceGroupRequest;
    } & CallOptions,
  ): Promise<models.CreateServiceGroupResponse> {
    return this.request<models.CreateServiceGroupResponse>(
      {
        method: "POST",
        path: `/v1/services`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Delete Service Group by UUID
   */
  deleteServiceGroupByUuid(
    uuid: string,
    params: CallOptions = {},
  ): Promise<models.DeleteServiceGroupsResponse> {
    return this.request<models.DeleteServiceGroupsResponse>(
      {
        method: "DELETE",
        path: `/v1/services/${uuid}`,
      },
      params,
    );
  }

  /**
   * Delete Service Groups
   */
  deleteServiceGroups(
    params: {
      body: models.NameOrUUID[];
    } & CallOptions,
  ): Promise<models.DeleteServiceGroupsResponse> {
    return this.request<models.DeleteServiceGroupsResponse>(
      {
        method: "DELETE",
        path: `/v1/services`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Get Service Group by UUID
   */
  getServiceGroupByUuid(
    uuid: string,
    params: {
      details?: boolean;
    } & CallOptions = {},
  ): Promise<models.GetServiceGroupsResponse> {
    return this.request<models.GetServiceGroupsResponse>(
      {
        method: "GET",
        path: `/v1/services/${uuid}`,
        query: {
          details: params["details"],
        },
      },
      params,
    );
  }

  /**
   * List Service Groups
   */
  getServiceGroups(
    params: {
      uuid?: string[];
      name?: string[];
      details?: boolean;
      count?: number;
      from?: string;
      order?: models.PaginationOrder;
      sortby?: models.PaginationSortBy;
    } & CallOptions = {},
  ): Promise<models.GetServiceGroupsResponse> {
    return this.request<models.GetServiceGroupsResponse>(
      {
        method: "GET",
        path: `/v1/services`,
        query: {
          uuid: params["uuid"],
          name: params["name"],
          details: params["details"],
          count: params["count"],
          from: params["from"],
          order: params["order"],
          sortby: params["sortby"],
        },
      },
      params,
    );
  }

  /**
   * Update Service Group by UUID
   */
  updateServiceGroupByUuid(
    uuid: string,
    params: {
      body: models.UpdateServiceGroupByUUIDRequestBody;
    } & CallOptions,
  ): Promise<models.UpdateServiceGroupsResponse> {
    return this.request<models.UpdateServiceGroupsResponse>(
      {
        method: "PATCH",
        path: `/v1/services/${uuid}`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Update Service Groups
   */
  updateServiceGroups(
    params: {
      body: models.UpdateServiceGroupsRequestItem[];
    } & CallOptions,
  ): Promise<models.UpdateServiceGroupsResponse> {
    return this.request<models.UpdateServiceGroupsResponse>(
      {
        method: "PATCH",
        path: `/v1/services`,
        body: params.body,
      },
      params,
    );
  }
}
