// Code generated by openapi-gen; DO NOT EDIT.
import { ApiClient, type CallOptions } from "../../core/http.js";
import type * as models from "./models.gen.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `Users` resource. Methods return the raw response envelope.
 */
export class UsersApi extends ApiClient {
  /**
   * Add Users
   */
  addUsers(
    params: {
      body: models.AddUsersRequest;
    } & CallOptions,
  ): Promise<models.AddUsersResponse> {
    return this.request<models.AddUsersResponse>(
      {
        method: "POST",
        path: `/v1/users`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Get Current User Quotas
   */
  getUser(params: CallOptions = {}): Promise<models.QuotasResponse> {
    return this.request<models.QuotasResponse>(
      {
        method: "GET",
        path: `/v1/users/quotas`,
      },
      params,
    );
  }

  /**
   * Get User Quotas by UUID
   */
  getUserByUuid(uuid: string, params: CallOptions = {}): Promise<models.QuotasResponse> {
    return this.request<models.QuotasResponse>(
      {
        method: "GET",
        path: `/v1/users/${uuid}/quotas`,
      },
      params,
    );
  }
}
