// Code generated by openapi-gen; DO NOT EDIT.
import { ApiClient, type CallOptions } from "../../core/http.js";
import type * as models from "./models.gen.js";

/**
 * Low-level "plumbing" client for the {@link https://unikraft.com|Unikraft
 * Cloud} `Volumes` resource. Methods return the raw response envelope.
 */
export class VolumesApi extends ApiClient {
  /**
   * Attach Volume by UUID
   */
  attachVolumeByUuid(
    uuid: string,
    params: {
      body: models.AttachVolumeByUUIDRequestBody;
    } & CallOptions,
  ): Promise<models.AttachVolumesResponse> {
    return this.request<models.AttachVolumesResponse>(
      {
        method: "PUT",
        path: `/v1/volumes/${uuid}/attach`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Attach Volumes
   */
  attachVolumes(
    params: {
      body: models.AttachVolumesRequestItem[];
    } & CallOptions,
  ): Promise<models.AttachVolumesResponse> {
    return this.request<models.AttachVolumesResponse>(
      {
        method: "PUT",
        path: `/v1/volumes/attach`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Clone Volume by UUID
   */
  cloneVolumeByUuid(
    uuid: string,
    params: {
      body: models.CloneVolumeByUUIDRequestBody;
    } & CallOptions,
  ): Promise<models.CloneVolumesResponse> {
    return this.request<models.CloneVolumesResponse>(
      {
        method: "POST",
        path: `/v1/volumes/${uuid}/clone`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Clone Volumes
   */
  cloneVolumes(
    params: {
      body: models.CloneVolumesRequestItem[];
    } & CallOptions,
  ): Promise<models.CloneVolumesResponse> {
    return this.request<models.CloneVolumesResponse>(
      {
        method: "POST",
        path: `/v1/volumes/clone`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Create template volume
   */
  createTemplateVolume(
    params: {
      body: models.NameOrUUID[];
    } & CallOptions,
  ): Promise<models.CreateTemplateVolumesResponse> {
    return this.request<models.CreateTemplateVolumesResponse>(
      {
        method: "POST",
        path: `/v1/volumes/templates`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Create Volume
   */
  createVolume(
    params: {
      body: models.CreateVolumeRequest;
    } & CallOptions,
  ): Promise<models.CreateVolumeResponse> {
    return this.request<models.CreateVolumeResponse>(
      {
        method: "POST",
        path: `/v1/volumes`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Delete template volume by UUID
   */
  deleteTemplateVolumeByUuid(
    uuid: string,
    params: CallOptions = {},
  ): Promise<models.DeleteTemplateVolumesResponse> {
    return this.request<models.DeleteTemplateVolumesResponse>(
      {
        method: "DELETE",
        path: `/v1/volumes/templates/${uuid}`,
      },
      params,
    );
  }

  /**
   * Delete template volumes
   */
  deleteTemplateVolumes(
    params: {
      body: models.NameOrUUID[];
    } & CallOptions,
  ): Promise<models.DeleteTemplateVolumesResponse> {
    return this.request<models.DeleteTemplateVolumesResponse>(
      {
        method: "DELETE",
        path: `/v1/volumes/templates`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Delete Volume by UUID
   */
  deleteVolumeByUuid(
    uuid: string,
    params: CallOptions = {},
  ): Promise<models.DeleteVolumesResponse> {
    return this.request<models.DeleteVolumesResponse>(
      {
        method: "DELETE",
        path: `/v1/volumes/${uuid}`,
      },
      params,
    );
  }

  /**
   * Delete Volumes
   */
  deleteVolumes(
    params: {
      body: models.NameOrUUID[];
    } & CallOptions,
  ): Promise<models.DeleteVolumesResponse> {
    return this.request<models.DeleteVolumesResponse>(
      {
        method: "DELETE",
        path: `/v1/volumes`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Detach Volume by UUID
   */
  detachVolumeByUuid(
    uuid: string,
    params: {
      body: models.DetachVolumeByUUIDRequestBody;
    } & CallOptions,
  ): Promise<models.DetachVolumesResponse> {
    return this.request<models.DetachVolumesResponse>(
      {
        method: "PUT",
        path: `/v1/volumes/${uuid}/detach`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Detach Volumes
   */
  detachVolumes(
    params: {
      body: models.DetachVolumesRequestItem[];
    } & CallOptions,
  ): Promise<models.DetachVolumesResponse> {
    return this.request<models.DetachVolumesResponse>(
      {
        method: "PUT",
        path: `/v1/volumes/detach`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Get template volume by UUID
   */
  getTemplateVolumeByUuid(
    uuid: string,
    params: {
      details?: boolean;
    } & CallOptions = {},
  ): Promise<models.GetTemplateVolumesResponse> {
    return this.request<models.GetTemplateVolumesResponse>(
      {
        method: "GET",
        path: `/v1/volumes/templates/${uuid}`,
        query: {
          details: params["details"],
        },
      },
      params,
    );
  }

  /**
   * List template volumes
   */
  getTemplateVolumes(
    params: {
      uuid?: string[];
      name?: string[];
      details?: boolean;
      count?: number;
      from?: string;
      tags?: string[];
      order?: models.PaginationOrder;
      sortby?: models.PaginationSortBy;
    } & CallOptions = {},
  ): Promise<models.GetTemplateVolumesResponse> {
    return this.request<models.GetTemplateVolumesResponse>(
      {
        method: "GET",
        path: `/v1/volumes/templates`,
        query: {
          uuid: params["uuid"],
          name: params["name"],
          details: params["details"],
          count: params["count"],
          from: params["from"],
          tags: params["tags"],
          order: params["order"],
          sortby: params["sortby"],
        },
      },
      params,
    );
  }

  /**
   * Get Volume by UUID
   */
  getVolumeByUuid(
    uuid: string,
    params: {
      details?: boolean;
    } & CallOptions = {},
  ): Promise<models.GetVolumesResponse> {
    return this.request<models.GetVolumesResponse>(
      {
        method: "GET",
        path: `/v1/volumes/${uuid}`,
        query: {
          details: params["details"],
        },
      },
      params,
    );
  }

  /**
   * List Volumes
   */
  getVolumes(
    params: {
      uuid?: string[];
      name?: string[];
      details?: boolean;
      count?: number;
      from?: string;
      tags?: string[];
      order?: models.PaginationOrder;
      sortby?: models.PaginationSortBy;
    } & CallOptions = {},
  ): Promise<models.GetVolumesResponse> {
    return this.request<models.GetVolumesResponse>(
      {
        method: "GET",
        path: `/v1/volumes`,
        query: {
          uuid: params["uuid"],
          name: params["name"],
          details: params["details"],
          count: params["count"],
          from: params["from"],
          tags: params["tags"],
          order: params["order"],
          sortby: params["sortby"],
        },
      },
      params,
    );
  }

  /**
   * Update template volume by UUID
   */
  updateTemplateVolumeByUuid(
    uuid: string,
    params: {
      body: models.UpdateTemplateVolumeByUUIDRequestBody;
    } & CallOptions,
  ): Promise<models.UpdateTemplateVolumesResponse> {
    return this.request<models.UpdateTemplateVolumesResponse>(
      {
        method: "PATCH",
        path: `/v1/volumes/templates/${uuid}`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Update template volumes
   */
  updateTemplateVolumes(
    params: {
      body: models.UpdateTemplateVolumesRequestItem[];
    } & CallOptions,
  ): Promise<models.UpdateTemplateVolumesResponse> {
    return this.request<models.UpdateTemplateVolumesResponse>(
      {
        method: "PATCH",
        path: `/v1/volumes/templates`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Update Volume by UUID
   */
  updateVolumeByUuid(
    uuid: string,
    params: {
      body: models.UpdateVolumeByUUIDRequestBody;
    } & CallOptions,
  ): Promise<models.UpdateVolumesResponse> {
    return this.request<models.UpdateVolumesResponse>(
      {
        method: "PATCH",
        path: `/v1/volumes/${uuid}`,
        body: params.body,
      },
      params,
    );
  }

  /**
   * Update Volumes
   */
  updateVolumes(
    params: {
      body: models.UpdateVolumesRequestItem[];
    } & CallOptions,
  ): Promise<models.UpdateVolumesResponse> {
    return this.request<models.UpdateVolumesResponse>(
      {
        method: "PATCH",
        path: `/v1/volumes`,
        body: params.body,
      },
      params,
    );
  }
}
